language: node_js
node_js:
  - "stable"
env:
  - NODE_ENV="production"

notifications:
  email:
    recipients:
      - jquinon1@eafit.edu.co
      - abedoy19@eafit.edu.co
      - vquinte3@eafit.edu.co
    on_success: never # default: change
    on_failure: always # default: always

services:
  - mongodb
addons:
   apt:
     update: true  
before_script:
  - cd biofeedbackWebApp
  - npm install
script: npm test
