language: node_js
node_js:
  - "stable"
env:
  - NODE_ENV="production"
  
services:
  - mongodb
  
 addons:
    apt:
      update: true
  
before_script:
  - cd biofeedbackWebApp
  - npm install
script: npm start
