language: node_js
node_js:
  - "stable"
env:
  - NODE_ENV="production"
  
services:
  - mongodb
notifications:
  email:
    recipients:
      - jquinon1@eafit.edu.co
      - abedoy19@eafit.edu.co
      - vquinte3@eafit.edu.co
addons:
   apt:
     update: true  
before_script:
  - cd biofeedbackWebApp
script: npm install
